outputs = "All"
position = "Top"
enable_esc_key = true

[modules]
left = [ [ "Workspaces" ] ]
center = [ "WindowTitle" ]
right = [ "SystemInfo", [  "Tray", "Clock", "Privacy", "Settings" ] ]

[system_info]
indicators = [ "Cpu", "Memory", "Temperature" ]

[system_info.cpu]
warn_threshold = 60
alert_threshold = 80

[system_info.memory]
warn_threshold = 70
alert_threshold = 85

[system_info.disk]
warn_threshold = 80
alert_threshold = 90

[system_info.temperature]
warn_threshold = 60
alert_threshold = 80
sensor = "acpitz temp1"


[tray]

[appearance]
scale_factor = 1.0
style = "Solid"
